#! /bin/sh

ask() {
    # http://djm.me/ask
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question - use /dev/tty in case stdin is redirected from somewhere else
        read -p "$1 [$prompt] " REPLY </dev/tty

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac

    done
}

echo "Generate test width copies."
if ask "Are you sure?"; then
    for width in 10 20 40 60 80
    do
        echo "Copying cli-100.js to cli-$width.js"
        rm test/cli-$width.js 2>/dev/null
        cp test/cli-100.js test/cli-$width.js
    done
    ava --verbose
fi
