#! /bin/sh

ask() {
    # http://djm.me/ask
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question - use /dev/tty in case stdin is redirected from somewhere else
        read -p "$1 [$prompt] " REPLY </dev/tty

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac

    done
}

echo "Generate test fixture output."
echo "Verify truwrap output correctness before regenerating output fixtures."
if ask "Are you sure?"; then
    for right in 0 1 5
    do
        for left in 0 1 2 5 10
        do
            for width in 10 20 40 60 80 100
            do
        	   echo "Soft wrap to width = $width, left = $left, right = $right"
                cat test/fixtures/in/lorem.txt | bin/truwrap.js --left $left --right $right --width $width > test/fixtures/out/lorem-soft-$width-$left-$right.txt

                echo "Soft tabbed wrap to width = $width, left = $left, right = $right"
                cat test/fixtures/in/tabbed.txt | bin/truwrap.js --left $left --right $right --width $width > test/fixtures/out/tabbed-soft-$width-$left-$right.txt

                echo "Hard wrap to width = $width, left = $left, right = $right"
                cat test/fixtures/in/lorem.txt | bin/truwrap.js --left $left --right $right --width $width --mode hard > test/fixtures/out/lorem-hard-$width-$left-$right.txt

                echo "Hard tabbed wrap to width = $width, left = $left, right = $right"
                cat test/fixtures/in/tabbed.txt | bin/truwrap.js --left $left --right $right --width $width --mode hard > test/fixtures/out/tabbed-hard-$width-$left-$right.txt

                echo "Keep wrap to width = $width, left = $left, right = $right"
                cat test/fixtures/in/ls.txt | bin/truwrap.js --left $left --right $right --width $width --mode keep > test/fixtures/out/ls-keep-$width-$left-$right.txt

            	echo "Stamp: "Hello %s!" World width = $width, left = $left, right = $right"
                bin/truwrap.js -s "Hello %s!" World --left $left --right $right --width $width > test/fixtures/out/stamp-$width-$left-$right.txt
            done
        done
    done
    for width in 40 60 80 100
    do
        echo "Panel: width = $width, left = 0, right = 0"
        cat test/fixtures/in/panel.txt | bin/truwrap.js --panel --left 0 --right 0 --width $width > test/fixtures/out/panel-$width-0-0.txt
    done
    ava --verbose
fi
